/**
 * Normalize a design-record key to a candidate CSS property name: strip an
 * optional `cf` prefix and camelCase kebab/snake (`cf-font-size` → `fontSize`).
 */
export function toCssKey(key: string): string {
  const stripped = key.replace(/^cf[-_]?/, '');
  const base = stripped || key; // `cf` alone → keep original
  return base
    .replace(/[-_]+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
    .replace(/^([A-Z])/, (c) => c.toLowerCase());
}

/** Whether a normalized key names a CSS property `toCss` will emit. */
export function isCssProperty(normalizedKey: string): boolean {
  return CSS_PROPERTIES.has(normalizedKey);
}

/** Whitelist of CSS property names (camelCase) `toCss` emits. Extend as needed. */
export const CSS_PROPERTIES: ReadonlySet<string> = new Set([
  // Box model / sizing
  'width',
  'minWidth',
  'maxWidth',
  'height',
  'minHeight',
  'maxHeight',
  'margin',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'marginBlock',
  'marginInline',
  'padding',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'paddingBlock',
  'paddingInline',
  'boxSizing',
  'aspectRatio',
  // Positioning / display
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'inset',
  'zIndex',
  'overflow',
  'overflowX',
  'overflowY',
  'visibility',
  'float',
  'clear',
  // Flexbox / grid
  'flex',
  'flexDirection',
  'flexWrap',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexBasis',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'alignItems',
  'alignContent',
  'alignSelf',
  'placeItems',
  'placeContent',
  'gap',
  'rowGap',
  'columnGap',
  'order',
  'grid',
  'gridTemplate',
  'gridTemplateColumns',
  'gridTemplateRows',
  'gridTemplateAreas',
  'gridColumn',
  'gridRow',
  'gridArea',
  'gridAutoFlow',
  'gridAutoColumns',
  'gridAutoRows',
  // Typography
  'color',
  'font',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'fontStyle',
  'fontVariant',
  'lineHeight',
  'letterSpacing',
  'wordSpacing',
  'textAlign',
  'textAlignLast',
  'textDecoration',
  'textDecorationLine',
  'textDecorationColor',
  'textDecorationStyle',
  'textTransform',
  'textOverflow',
  'textIndent',
  'textShadow',
  'whiteSpace',
  'wordBreak',
  'wordWrap',
  'overflowWrap',
  'writingMode',
  'verticalAlign',
  // Background
  'background',
  'backgroundColor',
  'backgroundImage',
  'backgroundPosition',
  'backgroundSize',
  'backgroundRepeat',
  'backgroundAttachment',
  'backgroundClip',
  'backgroundOrigin',
  'backgroundBlendMode',
  // Border / outline
  'border',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'borderTop',
  'borderRight',
  'borderBottom',
  'borderLeft',
  'borderRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'outline',
  'outlineWidth',
  'outlineStyle',
  'outlineColor',
  'outlineOffset',
  // Effects
  'opacity',
  'boxShadow',
  'filter',
  'backdropFilter',
  'mixBlendMode',
  'transform',
  'transformOrigin',
  'transition',
  'transitionProperty',
  'transitionDuration',
  'transitionTimingFunction',
  'transitionDelay',
  'animation',
  'cursor',
  'pointerEvents',
  'userSelect',
  // Misc
  'content',
  'listStyle',
  'listStyleType',
  'listStylePosition',
  'objectFit',
  'objectPosition',
  'fill',
  'stroke',
  'strokeWidth',
]);
